language: python
python: "3.8"
cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt install -y libxtst6 libnss3 libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0
  - sudo apt install xvfb

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt

script:
    - python setup.py bdist_wheel
    - pip install .
    - xvfb-run --server-args="-screen 0 1024x768x24" python tests/tests.py

deploy:
  - provider: pypi
    username: __token__
    distributions: bdist_wheel
    skip_existing: true
    password:
      secure: KU9vH29E0dYLm8oNEPwMnWVgvePbuztWpY2cjuyJTGT7J3nWGrcPa/6pEmjwZv2UQLD7ll6CEbD5hZHrUmr7A01oZpH6d6GfNfINIipbQcy5t6vGjjjNawazXz3VOg5TD6VcgmJNUD+pi4/Yye2536tlLa77awqh2UoLW7hGTfAsPCIVEZ/sCK4NOSnZAoMtyndkHiNzkpbC6UIuzjftAK81u65rpNgffLVCIdGEaoeBrRv1uqUTbqfj/kIOj70J/Fzz10ENIKUfxX2ppdtdOS9TvbSpEaLEy9NQ/Q26TQeHVHTsVCUS+zGbM+5B5MIjZ/WxBHbPLtLVaFWQQUChI5hQs9Ok9H7hOQEmqCLFNqvoDEsFPDfuiHEkL9SVYJV04UgVJrdgV0cqbFCY86PB0tJ1RF51WZjIigzgtm3cwm1RB2pzYnIFPfwBavA3s7hLLLsv2dOG22KEY3sG3XV4LIOH0eS4J1XuH5GrmbzMghQ6MxFF1s0KdU2s14G9NBpG9jAyshhXsvgHxE1fejvKys/7RXV5ERAScfgQYNV/0aHz3BeOetVnqvaw5AYAgswxT1+9X1lQC3eYvjt9KkgiNBUHpR/+7oZqCpbiiMv7Bqm43/h08I0xh1vlKD9wfQqK9FgdGagfhPbr9/u3zvbRUkRnwwuiSfYkCBovkjGkoT8=
    on:
      branch:
        - master 
